name: Command via SSH

on:
  pull_request
    branches:
      - "sites/carl-elefante"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull git OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd public_html/wp-content/themes/starting-point && git checkout sites/carl-elefante && git pull origin sites/carl-elefante
          host: host.hingemarketing.com
          username: carlelefante
          privateKey: ${{ secrets.HINGE_PRIVATE_KEY }}
          port: 522
# On host machine before hand, run:
# git config --global credential.helper store
# Then git pull origin master and enter username and password
