name: Command via SSH

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull git OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd odyssey.mifw.co/wp-content/themes/starting-point && git checkout odyssey && git pull origin odyssey
          host: madeinfortworth.com
          username: madeinfortworth
          privateKey: ${{ secrets.PRIVATE_KEY}}
          port: 522
# On host machine before hand, run:
# git config --global credential.helper store
# Then git pull origin master and enter username and password
